# Generated by Django 5.1.7 on 2026-03-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_livro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.categoria'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.editora'),
            preserve_default='TRUE',
        ),
    ]
